title: "## Change Logs"
# styles: [ "simple", "markdown", "gh-release" ]
style: gh-release
# group names
names: [ "Bug Fixes", "Features", "Performance Improvements", "Documentation", "Breaking Changes", "Refactor", "CI/CD", "Others" ]

filters:
  - name: msg_len
    min_len: 12
  - name: words_len
    min_len: 3
  - name: keyword
    keyword: format code
    exclude: true
  - name: keywords
    keyword: format code, action test
    exclude: true

# not match will be in Others group
rules:
  - name: Bug Fixes
    start_withs: [ "fix" ]
  - name: Features
    start_withs: [ "feat" ]
  - name: Performance Improvements
    start_withs: [ "perf" ]
  - name: Documentation
    start_withs: [ "docs" ]
  - name: Breaking Changes
    contains: [ "breaking:", "break:" ]
  - name: Refactor
    start_withs: [ "refactor" ]
  - name: CI/CD
    start_withs: [ "ci", "build" ]